
sidebar:
  menu:
    post: '[btn.blog](/)'
#    wiki: '[btn.wiki](/wiki/)'
    notes: '[笔记](/notes/)'
    more: '[更多](/more/)'

  widgets:
    # Recent update
    recent:
      layout: recent
      rss: /atom.xml # npm i hexo-generator-feed
      limit: 5 # Count of posts
    # TOC (valid only in layout:post/wiki)
    toc:
      layout: toc
      list_number: false
      min_depth: 2
      max_depth: 5

comments:
  service: beaudar
  beaudar:
    repo: fugangcui/blog-comments

open_graph:
  enable: false
  twitter_id: # for open_graph meta

tag_plugins:
  # {% image：图片开启缩放功能 %}
  image:
    fancybox: true

article:
  auto_excerpt: 200 # 摘要字数截取；
  auto_cover: false # 自动生成封面
  related_posts: # 相关文章推荐
    enable: true
    title: 您可能感兴趣的文章